_wandb:
    value:
        cli_version: 0.21.1
        e:
            pyohcc87xw5fcn9gvuyh7xed3daf82zq:
                args:
                    - PGAN
                    - -c
                    - config/config_Organoid.json
                    - -n
                    - Organoid
                    - --dir
                    - /data/dennyal/repos/HistoGWAS_PGAN
                    - --dimEmb
                    - "171"
                    - --dimOutput
                    - "1"
                    - --np_vis
                codePath: PGAN/train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3835391258624"
                        used: "38026072064"
                email: anddenny16@gmail.com
                executable: /data/dennyal/conda/envs/histogwas2/bin/python
                git:
                    commit: d225b44c6cb86b9d9b797e06604fccd95d07dd7c
                    remote: git@github.com:CollinsLabBioComp/HistoGWAS_PGAN.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-96e73951-d5e8-08b6-3a93-7ac06626863c
                host: cn0067
                memory:
                    total: "269910441984"
                os: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28
                program: /vf/users/dennyal/repos/HistoGWAS_PGAN/PGAN/train.py
                python: CPython 3.13.7
                root: /vf/users/dennyal/repos/HistoGWAS_PGAN/PGAN
                slurm:
                    cluster_name: biowulf
                    conf: /usr/local/slurm_etc.gpu/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0100000001000000
                    cpu_bind_list: "0x0100000001000000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "2"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: lesb
                    job_cpus_per_node: "2"
                    job_end_time: "1758575325"
                    job_gid: "62323"
                    job_id: "1272935"
                    job_name: sinteractive
                    job_nodelist: cn0067
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: global
                    job_start_time: "1758546525"
                    job_uid: "62323"
                    job_user: dennyal
                    jobid: "1272935"
                    launch_node_ipaddr: 10.1.201.9
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cn0067
                    prio_process: "0"
                    procid: "0"
                    pty_port: "34321"
                    pty_win_col: "100"
                    pty_win_row: "24"
                    srun_comm_host: 10.1.201.9
                    srun_comm_port: "35565"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "35565"
                    step_nodelist: cn0067
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/dennyal
                    submit_host: biowulf.nih.gov
                    task_pid: "2846521"
                    tasks_per_node: "2"
                    topology_addr: cn0067
                    topology_addr_pattern: node
                    umask: "0027"
                startedAt: "2025-09-22T13:29:09.134118Z"
                writerId: pyohcc87xw5fcn9gvuyh7xed3daf82zq
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
GDPP:
    value: null
Scale_iter:
    value: null
alphaJumpMode:
    value: null
alphaJumpVals:
    value: null
alphaNJumps:
    value: null
alphaSizeJumps:
    value: null
baseLearningRate:
    value: null
config:
    value:
        dimOutput: 1
        maxIterAtScale:
            - 48000
            - 96000
            - 96000
            - 96000
            - 96000
            - 96000
            - 1000000
configPath:
    value: config/config_Organoid.json
depthScales:
    value: null
dimEmb:
    value: 171
dimLatentVector:
    value: null
dimOutput:
    value: 1
dir:
    value: /data/dennyal/repos/HistoGWAS_PGAN
epsilonD:
    value: null
evalIter:
    value: 100
initBiasToZero:
    value: null
iterAlphaJump:
    value: null
lambdaGP:
    value: null
leakyness:
    value: null
lossMode:
    value: null
maxIterAtScale:
    value: null
miniBatchSize:
    value: null
miniBatchStdDev:
    value: null
model_name:
    value: PGAN
name:
    value: Organoid
no_vis:
    value: false
np_vis:
    value: true
overrides:
    value: false
partition_value:
    value: null
pathDB:
    value: /data/Collinslab/tcf7l2/organoid_anndata.h5ad
perChannelNormalization:
    value: null
restart:
    value: false
saveIter:
    value: 16000
weightConditionD:
    value: null
weightConditionG:
    value: null
